pluginManagement {
    repositories {
        maven {
            name = "NeoForged"
            url = "https://maven.neoforged.net/releases"
        }
        maven {
            name = "architectury"
            url = "https://maven.architectury.dev/"
        }
        maven {
            name = "FabricMC"
            url = "https://maven.fabricmc.net/"
        }
        gradlePluginPortal()
    }
}

rootProject.name = "muffins_thaidelight"

include(
        "common",
        "neoforge"
)